sonar.projectKey=it22113740_eventflow-user-service
sonar.projectName=eventflow-user-service
sonar.organization=it22113740

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
